version: "3.7"

services:
    app:
        ## dockerfile location
        build: .
        container_name: gocanada
        ports:
            - 3333:3333
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
